[package]
name = "tenet-crypto"
version = "0.1.0"
edition = "2021"

[dependencies]
chacha20poly1305 = { version = "0.10", features = ["std"] }
hpke = "0.11"
rand = "0.8"
rand_chacha = "0.3"

[dev-dependencies]
hex = "0.4"
